services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - ./pkg/common/envs/.env
    networks:
      - postgres-network
    volumes:
      - ./data/db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80  
    env_file:
      - ./pkg/common/envs/.env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./data/pgadmin-data/:/var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge